protected/modules/user/controllers/LogoutController.php
<?php

class LogoutController extends Controller
{
	public $defaultAction = 'logout';
	
	/**
	 * Logout the current user and redirect to returnLogoutUrl.
	 */
	public function actionLogout() {

            Yii::app()->user->logout();
            $facebook=SiteHelper::getFacbook();
            $user = $facebook->getUser();
             if(!empty($user)){
                $facebook->LogoutFaceBook();
            }


            $target = Yii::app()->createUrl("site/index");
            $this->redirect($target);
            
         
    }

}

protected/modules/user/controllers/UserController.php
<?php

class UserController extends Controller
{
	/**
	 * @var CActiveRecord the currently loaded data model instance.
	 */
	private $_model;

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return CMap::mergeArray(parent::filters(),array(
			'accessControl', // perform access control for CRUD operations
		));
	}
	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}	

	/**
	 * Displays a particular model.
	 */
	public function actionView()
	{
		$model = $this->loadModel();
		$this->render('view',array(
			'model'=>$model,
		));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('User', array(
			'criteria'=>array(
		        'condition'=>'status>'.User::STATUS_BANNED,
		    ),
				
			'pagination'=>array(
				'pageSize'=>Yii::app()->controller->module->user_page_size,
			),
		));

		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 */
	public function loadModel()
	{
		if($this->_model===null)
		{
			if(isset($_GET['id']))
				$this->_model=User::model()->findbyPk($_GET['id']);
			if($this->_model===null)
				throw new CHttpException(404,'The requested page does not exist.');
		}
		return $this->_model;
	}


	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the primary key value. Defaults to null, meaning using the 'id' GET variable
	 */
	public function loadUser($id=null)
	{
		if($this->_model===null)
		{
			if($id!==null || isset($_GET['id']))
				$this->_model=User::model()->findbyPk($id!==null ? $id : $_GET['id']);
			if($this->_model===null)
				throw new CHttpException(404,'The requested page does not exist.');
		}
		return $this->_model;
	}
}

protected/modules/user/views/user/_regis.php
<?php
$this->pageTitle = Yii::app()->name . ' - ' . UserModule::t("Registration");
$this->breadcrumbs = array(
    UserModule::t("Registration"),
);
?>



<?php if (Yii::app()->user->hasFlash('registration')): ?>
    <div class="success">
        <?php echo Yii::app()->user->getFlash('registration'); ?>
    </div>
<?php else: ?>

    <div class="form">


        <p class="note"><?php echo UserModule::t('Fields with <span class="required">*</span> are required.'); ?></p>

        <?php echo $form->errorSummary(array($model, $profile)); ?>

        <!--	<div class="row">-->
        <?php //echo $form->labelEx($model,'username');  ?>
        <?php // echo $form->textField($model,'username');  ?>
        <?php //echo $form->error($model,'username');  ?>
        <!--	</div>-->

        <div class="row-fluid">
            <?php echo $form->labelEx($model, 'password'); ?>
            <?php echo $form->passwordField($model, 'password'); ?>
            <?php echo $form->error($model, 'password'); ?>
            <p class="hint">
                <?php echo UserModule::t("Minimal password length 4 symbols."); ?>
            </p>



            <?php echo $form->labelEx($model, 'verifyPassword'); ?>
            <?php echo $form->passwordField($model, 'verifyPassword'); ?>
            <?php echo $form->error($model, 'verifyPassword'); ?>



            <?php echo $form->labelEx($model, 'email'); ?>
            <?php echo $form->textField($model, 'email'); ?>
            <?php echo $form->error($model, 'email'); ?>


            <?php
            $profileFields = $profile->getFields();
            if ($profileFields) {
                foreach ($profileFields as $field) {
                    ?>
                    <div class="row-fluid">
                        <?php echo $form->labelEx($profile, $field->varname); ?>
                        <?php
                        if ($widgetEdit = $field->widgetEdit($profile)) {
                            echo $widgetEdit;
                        } elseif ($field->range) {
                            echo $form->dropDownList($profile, $field->varname, Profile::range($field->range));
                        } elseif ($field->field_type == "TEXT") {
                            echo$form->textArea($profile, $field->varname, array('rows' => 6, 'cols' => 50));
                        } else {
                            echo $form->textField($profile, $field->varname, array('size' => 60, 'maxlength' => (($field->field_size) ? $field->field_size : 255)));
                        }
                        ?>
                        <?php echo $form->error($profile, $field->varname); ?>
                    </div>	
                    <?php
                }
            }
            ?>
            <?php if (UserModule::doCaptcha('registration')): ?>

                <?php echo $form->labelEx($model, 'verifyCode'); ?>

                <?php $this->widget('CCaptcha'); ?>
                <?php echo $form->textField($model, 'verifyCode'); ?>
                <?php echo $form->error($model, 'verifyCode'); ?>

                <p class="hint"><?php echo UserModule::t("Please enter the letters as they are shown in the image above."); ?>
                    <br/><?php echo UserModule::t("Letters are not case-sensitive."); ?></p>

            <?php endif; ?>

            <div class="submit">
                <div class="span4">
                    <?php echo CHtml::submitButton(Yii::t("site","Register")); ?>     
                </div>
            </div>


        </div><!-- form -->
    </div>
<?php endif; ?>

protected/modules/user/views/user/_user_menu.php
<?php 
$user_id = Yii::app()->user->id;
$model_user= UsersFaceBook::model()->findByPk($user_id);

$action= Yii::app()->controller->action->id;


?>

<div class="user-info-menu">

    <div class="background-lesson">
        <div class="lesson1-study">
            <h4 id="unit-19" class="major-lesson">   User  </h4>
        </div>
    </div>
    <div class="lesson-list"> 
        <div class="w-clearfix menu-list <?php if($action=="edit"){ echo "lesson-active"; } ?>">
          <span class="glyphicon glyphicon-chevron-right"></span> 
            <a href="<?php echo Yii::app()->createUrl("user/profile/edit");?>" class="menu-user"> Edit Profile </a>            
        </div>
        
         <?php //if(empty($model_user->facebook_id)){ ?>
        
<!--         <div class="w-clearfix lesson-all <?php if($action=="edit"){ echo "connectSocialNetwork"; } ?>">
            <img class="icon-lesson" src="images/affiliate_icon.png" width="50px">
            <a href="<?php echo Yii::app()->createUrl("user/profile/connectSocialNetwork");?>" class="detail-lesson"> Conect Social NetWork </a>            
        </div>-->
        
            
        <?php //} ?>
        <?php if(empty($model_user->password)){ ?>
          <span class="glyphicon glyphicon-chevron-right"></span> 
         <div class="w-clearfix menu-list <?php if($action=="createpassword"){echo "lesson-active";} ?>">
           
            <a href="<?php echo Yii::app()->createUrl("user/profile/createpassword");?>" class="menu-user"> Create Password to system </a>            
        </div>
        <?php }else{?>
        
        <div class="w-clearfix menu-list <?php if($action=="changepassword"){echo "lesson-active";} ?>">
              <span class="glyphicon glyphicon-chevron-right"></span> 
            <a href="<?php echo Yii::app()->createUrl("user/profile/changepassword");?>" class="menu-user"> Change password </a>            
        </div>
        
        
        <?php } ?>
        
        <div class="w-clearfix menu-list">
             <span class="glyphicon glyphicon-chevron-right"></span> 
            <a href="<?php echo Yii::app()->createUrl("user/logout");?>" class="menu-user"> Logout </a>            
        </div>

    </div>
    

    
</div>

protected/modules/user/views/user/index.php
<?php
$this->breadcrumbs=array(
	UserModule::t("Users"),
);
if(UserModule::isAdmin()) {
	$this->layout='//layouts/column2';
	$this->menu=array(
	    array('label'=>UserModule::t('Manage Users'), 'url'=>array('/user/admin')),
	    array('label'=>UserModule::t('Manage Profile Field'), 'url'=>array('profileField/admin')),
	);
}
?>

<h1><?php echo UserModule::t("List User"); ?></h1>

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'dataProvider'=>$dataProvider,
	'columns'=>array(
		array(
			'name' => 'username',
			'type'=>'raw',
			'value' => 'CHtml::link(CHtml::encode($data->username),array("user/view","id"=>$data->id))',
		),
		'create_at',
		'lastvisit_at',
	),
)); ?>

protected/modules/user/views/user/login.php
<script type="text/javascript">
    $(document).ready(function() {
       document.title = "Login - CourseCreek"; 

    });
</script>

<?php $user_id = Yii::app()->user->id; ?>
<?php if (empty($user_id) || $user_id == "0") { ?>
<div class="gray-row">
    <div class="container-full">
        <div class="form-box">
        <div class="w-container login-tab-box">
        <div class="w-form login-signup-form full-access">
   
            
            <div id="login-block" class="login-signup-panel login-tab-box" style="">
             <h1 class="head-form"> Login </h1>
                
                 <?php
                        $form = $this->beginWidget('CActiveForm', array(
                            'id' => 'login',
                            'action' => Yii::app()->createUrl('/user/login/login'),
                            'enableClientValidation' => true,
                            'enableAjaxValidation' => true,
                            'htmlOptions' => array("role" => "form"),
                            'clientOptions' => array(
                                'validateOnSubmit' => true,
                            ),
                        ));
                        ?> 
                
                
                 <?php echo $form->errorSummary(array($model)); ?>
                
              <div class="form-group">
               <label for="exampleInputPassword1">Student Id:*</label>
               <?php echo $form->textField($model, 'username',array("placeholder"=>"อีเมล","id"=>"exampleInputEmail1","class"=>"form-control")); ?>
               <?php //echo $form->error($model, 'username'); ?>
              </div> 
              
              
             <div class="form-group">
                <label for="exampleInputPassword1">Password*</label>
                <?php echo $form->PasswordField($model, 'password',array("placeholder"=>"รหัสผ่าน","id"=>"inputPassword3","class"=>"form-control")); ?>
                <!--<input type="password" name="UserLogin[password]" class="form-control" id="exampleInputPassword1" placeholder="Password">-->
                <input type="hidden" name="is_box" value="<?php echo $inbox; ?>">
             </div>
              
              
              <div class="checkbox">
                <label>
                   <input name="rememberMe" type="checkbox" class="" checked value="1"> <?php echo Yii::t("site","Remember me"); ?>
                </label>
                  
              </div>
              
               <button type="submit" class="btn btn-primary"> เข้าาสู่ระบบ </button>
               
                <?php $reset_link = Yii::app()->createUrl("/user/recovery"); ?>
                <a href="<?php echo $reset_link ?>"><?php echo Yii::t("site","Reset Password"); ?> [Reset Password] </a>
                
                 <?php $this->endWidget(); ?>
                  </div>
            
        </div>
     </div>        
        
</div>

<?php } ?>
</div>
</div>    
    

protected/modules/user/views/user/login_ajax.php
<script type="text/javascript">
    $(document).ready(function() {
       document.title = "Login - CourseCreek"; 

    });
</script>
<?php $user_id = Yii::app()->user->id; ?>
<?php if (empty($user_id) || $user_id == "0") { ?>


<div id="content-access" class="section hero section-course">
        <div class="w-container login-tab-box">
        <div class="w-form login-signup-form full-access">
        <?php $member_regis_link = Yii::app()->createUrl('/user/registration/registration') ?>   
        <div class="signup-login-toggle">
            <a id="regis_ajax" class="signup-tab inactive" href="#"><?php echo Yii::t("site", "Register"); ?></a><a id="signIn-tab" class="login-tab active" href="#"><?php echo Yii::t("site", "Login"); ?></a>
        </div> 
            
            <div id="login-block" class="login-signup-panel login-tab-box" style="">
                
              <?php 
                if(!empty($course_id)){
                $this->widget('FaceBookLogin',array("word"=>"เข้าสู่ระบบ ด้วย Facebook","course_id"=>$course_id)); 
                }else{
                    $this->widget('FaceBookLogin',array("word"=>"เข้าสู่ระบบ ด้วย Facebook")); 
                }
              ?>  
                
                
             <br/>                
                     <?php
                        $form = $this->beginWidget('CActiveForm', array(
                            'id' => 'login_ajax',
                            'action' => Yii::app()->createUrl('user/login/validateLoginAjax'),
                            'enableClientValidation' => true,
                            'enableAjaxValidation' => true,
//                            'htmlOptions' => array("role" => "form"),
                            'clientOptions' => array(
                                'validateOnSubmit' => false,
                            ),
                        ));
                        ?> 
               
              <p class="text-center"> หรือเข้าสู่ระบบด้วยอีเมลล์ </p>   
             
              
              
              <div class="errorSummary" style="display: none">
                  Username หรือ Password ไม่ถูกต้อง
              </div>
              
              <div class="form-group">
               <label for="exampleInputPassword1">อีเมล*</label>            
               <input placeholder="อีเมล" id="username" class="form-control" name="username" type="text">
               <?php //echo $form->error($model, 'username'); ?>
              </div> 
              
              
               <div class="form-group">
                <label for="exampleInputPassword1">รหัสผ่าน*</label>
          
                <input type="password" name="รหัสผ่าน" class="form-control" id="password" placeholder="Password">
                <input type="hidden" name="is_box" value="<?php echo $inbox; ?>">
             </div>
              
              
              <?php if(!empty($course_id)){ ?>
                <input id='course-id' type="hidden" name='course_id' valuse='<?php echo $course_id; ?>'>   
                <input type="hidden" id="redirect_url" name="redirect_url" value="<?php echo Yii::app()->createUrl("course/default/studyCourse",array("courseId"=>$course_id));?>">
              <?php } ?>
              
              <div class="checkbox">
                <label>
                   <input id="remember" type="checkbox" name="rememberMe" class="" checked value="1"> <?php echo Yii::t("site","Remember me"); ?>
                </label>
                  
              </div>
              
               <button type="button" class="btn btn-primary" id="accept-form"> Login </button>      
                              
               <?php $this->endWidget(); ?>
                  
            </div>
            
        </div>
     </div>        
        
</div>





 <script type="text/javascript">
               jQuery.noConflict();
               $(document).ready(function(){
                  $("#accept-form").click(function(){                   
                   var username = $("#username").val();
                   var password = $("#password").val();   
                   var remember = $("#remember").val();
                   var course_id= $("#course-id").val();
                   var redirect_url = $("#redirect_url").val();               
               
                    $.ajax({
                        url:"<?php echo Yii::app()->createUrl("user/login/ValidateLoginAjax");?>",
                        type : "POST",
                        data: {username: username, password: password, remember: remember},
                        dataType: 'html',
                        beforeSend:function(){
                            $(".errorSummary").hide();       
                        },
                        success:function(result){                    
                            if(result == "success"){
                                $.fancybox.close();
                                if(redirect_url==""){
                                    location.reload();
                                }else{
                                     window.location.replace(redirect_url);
                                }
                                
//                               
                                
                                
                                $(".errorSummary").html(" ");  
                            }else{
                                $(".errorSummary").show();                                
                            }
                        }});
              });
              
              $("#regis_ajax").click(function(){
              $.ajax({
                        url:"<?php echo Yii::app()->createUrl("user/registration/registrationAjax");?>",                       
                        dataType: 'html',                       
                        success:function(result){
                            $("#content-access").html(result);
                           
                        }});           
              });
            
            
            });
               
               
              
              
              
</script>
<?php } ?>

protected/modules/user/views/user/login_fromextension.php
<?php
$this->pageTitle=Yii::app()->name . ' - '.UserModule::t("Login");
$this->breadcrumbs=array(
	UserModule::t("Login"),
);
?>

<h1><?php echo UserModule::t("Login"); ?></h1>

<?php if(Yii::app()->user->hasFlash('loginMessage')): ?>

<div class="success">
	<?php echo Yii::app()->user->getFlash('loginMessage'); ?>
</div>

<?php endif; ?>

<p><?php echo UserModule::t("Please fill out the following form with your login credentials:"); ?></p>

<div class="form">
<?php echo CHtml::beginForm(); ?>

	<p class="note"><?php echo UserModule::t('Fields with <span class="required">*</span> are required.'); ?></p>
	
	<?php echo CHtml::errorSummary($model); ?>
	
	<div class="row">
		<?php echo CHtml::activeLabelEx($model,'username'); ?>
		<?php echo CHtml::activeTextField($model,'username') ?>
	</div>
	
	<div class="row">
		<?php echo CHtml::activeLabelEx($model,'password'); ?>
		<?php echo CHtml::activePasswordField($model,'password') ?>
	</div>
	
	<div class="row">
		<p class="hint">
		<?php echo CHtml::link(UserModule::t("Register"),Yii::app()->getModule('user')->registrationUrl); ?> | <?php echo CHtml::link(UserModule::t("Lost Password?"),Yii::app()->getModule('user')->recoveryUrl); ?>
		</p>
	</div>
	
	<div class="row rememberMe">
		<?php echo CHtml::activeCheckBox($model,'rememberMe'); ?>
		<?php echo CHtml::activeLabelEx($model,'rememberMe'); ?>
	</div>

	<div class="row submit">
		<?php echo CHtml::submitButton(UserModule::t("Login")); ?>
	</div>
	
<?php echo CHtml::endForm(); ?>
</div><!-- form -->


<?php
$form = new CForm(array(
    'elements'=>array(
        'username'=>array(
            'type'=>'text',
            'maxlength'=>32,
        ),
        'password'=>array(
            'type'=>'password',
            'maxlength'=>32,
        ),
        'rememberMe'=>array(
            'type'=>'checkbox',
        )
    ),

    'buttons'=>array(
        'login'=>array(
            'type'=>'submit',
            'label'=>'Login',
        ),
    ),
), $model);
?>

protected/modules/user/views/user/message.php
<?php $this->pageTitle=Yii::app()->name . ' - '.UserModule::t("Login"); ?>

<h1><?php echo $title; ?></h1>

<div class="form">
<?php echo $content; ?>

</div><!-- yiiForm -->

protected/modules/user/views/user/regis.php
<script type="text/javascript">

    $(document).ready(function() {

        $("#regis_button").click(function(){
            $("#regis").submit();
        });
           $("body").removeClass("front").addClass("login");
        
    });
    
     
</script>
<?php $user_id = Yii::app()->user->id; ?>
<?php if (empty($user_id) || $user_id == "0") { ?>
<div class="body-login">
    <div id="maincontent">
        <div class="container-fluid">
            <div class="container">

                <!--warning-->
                <div class="row-fluid">                    
                    <div class="alert alert-info">
                        <i class="icon-warning-sign"></i> คุณยังไม่ได้เข้าสู่ระบบ กรุณาเข้าสู่ระบบหรือสมัครสมาชิกโดยกรอกแบบฟอร์มด้านล่างค่ะ
                    </div>                    
                </div>
                <!--warning-->

                <!--form-->
                <div class="row-fluid">
                    <div class="span2"></div>
                    
                        <?php
                        $form = $this->beginWidget('CActiveForm', array(
                            'id' => 'regis',
                            'action' => Yii::app()->createUrl('/user/registration/registration'),
                            'enableClientValidation' => true,
                            'enableAjaxValidation' => true,
                            'htmlOptions' => array("class" => "span8 login-form"),
                            'clientOptions' => array(
                                'validateOnSubmit' => true,
                            ),
                        ));
                        ?>
                    
                  

                        <div class="span12">
                            <div class="row-fluid">
                                <div class="span2"></div>
                                <div class="span8">
                                    <div class="row-fluid btn-group row-course" id="btn-group-user" data-toggle="buttons-radio">
                                        
                                        <button class="btn btn-user btn-primary <?php if($mode!="login"){ echo "active"; }?>" type="button" id="member">สมัครสมาชิก</button>
<!--                                        <button class="btn btn-user btn-primary" type="button" id="login" >เข้าสู่ระบบ</button>-->

                                        <?php $login_link= Yii::app()->createUrl('/user/login/login'); ?>
                                        <input type="button" value="     เข้าสู่ระบบ     " class="btn btn-user btn-primary" id="login" onClick="window.location.href='<?php echo $login_link;?>'">
                                    </div> <!-- btn-group -->
                                </div>
                                <div class="span2"></div>
                            </div>
                            
                            
                            
                            <br><br>
                            <div class="row-fluid line-lightgrey-wrapper row-course">&nbsp;</div>
                            <br><br>
                            
                    
                            <div id="member-regis" class="row-course"> 
                                
                                <?php $this->renderPartial("/user/_regis",array("form"=>$form,"mode"=>$mode));?>
                                
                            </div> <!-- member -->

                        </div><!-- span8 -->

                     <?php $this->endWidget(); ?>
                    <div class="span2"></div>
                    </>
                </div><!--form-->    
            </div><!-- container -->
        </div><!-- container-fluid -->
    </div><!-- content -->   
    

<?php } ?>

protected/modules/user/views/user/registration.php
<script type="text/javascript">
    $(document).ready(function() {
        document.title = "Register "; 

    });
</script>

<?php $user_id = Yii::app()->user->id; ?>
<?php if (empty($user_id) || $user_id == "0") { ?>
<div class="gray-row">
    <div class="container-full">
        <div class="form-box">
        <div class="w-container login-tab-box">
        <div class="w-form login-signup-form full-access">
   
            
            <div id="login-block" class="login-signup-panel login-tab-box" style="">
             <h1 class="head-form">  </h1>
                
        
                 <?php
                        $form = $this->beginWidget('CActiveForm', array(
                            'id' => 'Registration',
                            'action' => Yii::app()->createUrl('/user/registration/registration'),
                            'enableClientValidation' => true,
                            'enableAjaxValidation' => true,
                            'htmlOptions' => array("role" => "form"),
                            'clientOptions' => array(
                                'validateOnSubmit' => true,
                            ),
                        ));
                        ?> 
                
                
                 <?php echo $form->errorSummary(array($model)); ?>
                
              <div class="form-group">
               <label for="exampleInputPassword1">username*</label>
                <?php echo $form->textField($model, 'username',array("placeholder"=>"username","class"=>"form-control")); ?>
               <?php //echo $form->error($model, 'username'); ?>
              </div> 
             
              <div class="form-group">
               <label for="exampleInputPassword1">Email*</label>
                     <?php echo $form->textField($model, 'email',array("placeholder"=>"อีเมล","id"=>"exampleInputEmail1","class"=>"form-control")); ?>
               <?php //echo $form->error($model, 'username'); ?>
              </div> 
              
              
             <div class="form-group">
                <label for="exampleInputPassword1">รหัสผ่าน*</label>
                <?php echo $form->PasswordField($model, 'password',array("placeholder"=>"รหัสผ่าน","id"=>"inputPassword3","class"=>"form-control")); ?>
              </div>
              
              <div class="form-group">
                <label for="exampleInputPassword1">ยืนยันรหัสผ่าน*</label>
                <?php echo $form->PasswordField($model, 'verifyPassword',array("placeholder"=>"ยืนยันรหัสผ่าน","id"=>"inputPassword3","class"=>"form-control")); ?>
              </div>
              
              <div class="checkbox">
                <label>
                   <input name="rememberMe" type="checkbox" class="" checked value="1"> <?php echo Yii::t("site","Remember me"); ?>
                </label>
                  
              </div>
              
         
               <button type="submit" class="btn btn-primary"> สมัครสมาชิก </button> 
               
             
                
                 <?php $this->endWidget(); ?>
                  </div>
            
        </div>
     </div>        
        
</div>

<?php } ?>
</div>
</div>    
    

protected/modules/user/views/user/view.php
<?php
$this->breadcrumbs=array(
	UserModule::t('Users')=>array('index'),
	$model->username,
);
$this->layout='//layouts/column2';
$this->menu=array(
    array('label'=>UserModule::t('List User'), 'url'=>array('index')),
);
?>
<h1><?php echo UserModule::t('View User').' "'.$model->username.'"'; ?></h1>
<?php 

// For all users
	$attributes = array(
			'username',
	);
	
	$profileFields=ProfileField::model()->forAll()->sort()->findAll();
	if ($profileFields) {
		foreach($profileFields as $field) {
			array_push($attributes,array(
					'label' => UserModule::t($field->title),
					'name' => $field->varname,
					'value' => (($field->widgetView($model->profile))?$field->widgetView($model->profile):(($field->range)?Profile::range($field->range,$model->profile->getAttribute($field->varname)):$model->profile->getAttribute($field->varname))),

				));
		}
	}
	array_push($attributes,
		'create_at',
		array(
			'name' => 'lastvisit_at',
			'value' => (($model->lastvisit_at!='0000-00-00 00:00:00')?$model->lastvisit_at:UserModule::t('Not visited')),
		)
	);
			
	$this->widget('zii.widgets.CDetailView', array(
		'data'=>$model,
		'attributes'=>$attributes,
	));

?>